# Generated by Django 3.2.16 on 2023-01-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('number', models.FloatField(max_length=50)),
                ('date', models.DateField(default=False)),
                ('time', models.TimeField(default=False)),
                ('number_of_people', models.FloatField(verbose_name=10)),
            ],
        ),
    ]
