# Generated by Django 3.2.16 on 2023-01-21 16:31

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_guests',
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.TextField(default=builtins.any),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number',
            field=models.FloatField(default=builtins.any),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_people',
            field=models.FloatField(default=builtins.any, verbose_name=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=builtins.any),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=builtins.any),
        ),
    ]
