# Generated by Django 3.2.16 on 2023-01-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20230121_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_people',
            field=models.FloatField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=False),
        ),
    ]
